apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/zxiong/testrepo2?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: test-app1
    appstudio.openshift.io/component: testrepo2-fbc-matrix
    pipelines.appstudio.openshift.io/type: build
  name: testrepo2-fbc-matrix-on-pull-request
  namespace: zxiong-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/zxiong-tenant/testrepo2-fbc-matrix:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Dockerfile
  - name: image-url
    value: quay.io/redhat-user-workloads/ose-osc-tenant/osc-fbc-4-19:on-pr-51fa2f15aaa1dd73203cc636c3647c2ae02356d0
  - name: image-digest
    value: sha256:981e50cc51c449f319c8816b9d83124fed8e098d3eeba7afb69cf90b4d7f56a3
  - name: SOURCE_ARTIFACT
    value: "oci:quay.io/redhat-user-workloads/ose-osc-tenant/osc-fbc-4-19@sha256:19d20a2ef4bb6189e2215d6dfbad63bd769158292a8bf86d9f184786a6ac5f06"
  - name: LOAD_BALANCE
    value: "true"
  - name: NUM_BUCKETS
    value: "2"
  - name: "MAX_PARALLEL"
    value: "4"
  pipelineSpec:
    description: |
      This pipeline is ideal for building and verifying [file-based catalogs](https://konflux-ci.dev/docs/end-to-end/building-olm/#building-the-file-based-catalog).

      _Uses `buildah` to create a container image. Its build-time tests are limited to verifying the included catalog and do not scan the image.
      This pipeline is pushed as a Tekton bundle to [quay.io](https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-fbc-builder?tab=tags)_
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: .
      description: Path to the source code of an application's component from where
        to build image.
      name: path-context
      type: string
    - default: Dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "true"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ""
      description: Build dependencies to be prefetched
      name: prefetch-input
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like
        1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      type: string
    - default: "false"
      description: Build a source image.
      name: build-source-image
      type: string
    - default: "true"
      description: Add built image into an OCI image index
      name: build-image-index
      type: string
    - default: "false"
      description: Enable cache proxy configuration
      name: enable-cache-proxy
    - default: []
      description: Array of --build-arg values ("arg=value" strings) for buildah
      name: build-args
      type: array
    - default: ""
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
      name: build-args-file
      type: string
    - default:
      - linux/x86_64
      description: List of platforms to build the container images on. The available
        set of values is determined by the configuration of the multi-platform-controller.
      name: build-platforms
      type: array
    results:
      - name: TOTAL_IMAGES
        description: Total number of unique images
        value: $(tasks.extract-and-split.results.TOTAL_IMAGES)
      - name: BUCKETS_ARTIFACT
        description: OCI artifact containing buckets
        value: $(tasks.extract-and-split.results.BUCKETS_ARTIFACT)
    tasks:
    - name: extract-and-split
      timeout: "4h"
      params:
        - name: SOURCE_ARTIFACT
          value: $(params.SOURCE_ARTIFACT)
        - name: image-digest
          value: $(params.image-digest)
        - name: image-url
          value: $(params.image-url)
        - name: output-image
          value: $(params.output-image)
        - name: NUM_BUCKETS
          value: $(params.NUM_BUCKETS)
        - name: LOAD_BALANCE
          value: $(params.LOAD_BALANCE)
        - name: SIZE_FETCH_PARALLEL
          value: "5"
      taskRef:
        params:
        - name: name
          value: fbc-fips-extract-and-split-oci-ta
        - name: bundle
          value: quay.io/zxiong/fbc-fips-check-matrix:0.1.2
        - name: kind
          value: task
        resolver: bundles
      # Task 2: Process buckets in parallel (matrix on BUCKET_INDEX)
    - name: fips-check-buckets
      runAfter:
        - extract-and-split
      timeout: "4h"
      when:
        - input: "$(tasks.extract-and-split.results.TOTAL_IMAGES)"
          operator: notin
          values: ["0"]
      matrix:
        params:
          - name: BUCKET_INDEX
            value: $(tasks.extract-and-split.results.BUCKET_INDICES[*])
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/zxiong/fbc-fips-check-matrix:0.1.2
          - name: name
            value: fbc-fips-check-bucket-oci-ta
          - name: kind
            value: Task
      params:
        - name: BUCKETS_ARTIFACT
          value: $(tasks.extract-and-split.results.BUCKETS_ARTIFACT)
        - name: MAX_PARALLEL
          value: $(params.MAX_PARALLEL)
    workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-testrepo2-fbc-matrix
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
