---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/zxiong/testrepo1?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: test-app1
    appstudio.openshift.io/component: test-fbc-fips1
    pipelines.appstudio.openshift.io/type: build
  name: testrepo-fbc-test1-on-pull-request
spec:
  timeouts:
    pipeline: "4h"
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/zxiong-tenant/testrepo-2-test-tasl-upgrade:{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile
  - name: NUM_BUCKETS
    value: "5"
  - name: MAX_PARALLEL
    value: "2"
  pipelineSpec:
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: .
      description: Path to the source code of an application's component from where
        to build image.
      name: path-context
      type: string
    - default: Dockerfile
      description: Path to the Dockerfile inside the context specified by parameter
        path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ""
      description: Build dependencies to be prefetched
      name: prefetch-input
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like
        1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      type: string
    - default: "false"
      description: Build a source image.
      name: build-source-image
      type: string
    - default: "false"
      description: Add built image into an OCI image index
      name: build-image-index
      type: string
    - description: Number of parallel TaskRuns (buckets) to create
      name: NUM_BUCKETS
      type: string
      default: "2"
    - description: Maximum number of images to check in parallel
      name: MAX_PARALLEL
      type: string
      default: "5"
    tasks:
    #
    # TASK 1: Extract images, create OCI artifact, and generate bucket indices
    #
    - name: prepare-images-and-buckets
      timeout: "5m"
      params:
      - name: NUM_BUCKETS
        value: $(params.NUM_BUCKETS)
      taskSpec:
        params:
          - name: NUM_BUCKETS
            type: string
        results:
          - name: IMAGES_ARTIFACT
            type: string
            description: OCI reference to images artifact
          - name: BUCKET_INDICES
            type: array
            description: Array of bucket indices for matrix expansion
        volumes:
          - name: workdir
            emptyDir: {}
        stepTemplate:
          volumeMounts:
            - name: workdir
              mountPath: /var/workdir  
        steps:
          # Step 1: Extract images and split into bucket files
          - name: extract-and-split-images
            image: quay.io/konflux-ci/konflux-test:v1.4.41@sha256:afea44d83043be7f528ec2cacaeb0c3b69cdafdd86a1b930957def38400f8a6c
            env:
              - name: NUM_BUCKETS
                value: $(params.NUM_BUCKETS)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              echo "Extracting images from FBC..."
              mkdir -p /var/workdir/artifact-data

              # Simulate extracting images (replace with real extraction)
              # In real case, this would be from fbc-extract-images-oci-ta
              all_images=(
                "registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:094db84a1da5e8a575d0c9eade114fa30f4a2061064a338e3e032f3578f8082a"
                "registry.redhat.io/openshift4/ose-prom-label-proxy-rhel9@sha256:023cf36b1efe4b343dfcb26c43fd2984083f4532c6ebb1f4b7418a6e282e6f01"
                "registry.redhat.io/openshift4/ose-cli-rhel9@sha256:854608d87c79214118649df5bc96bd8f03794173489075cbd19e9f0419fb378d"
                "registry.redhat.io/openshift4/ose-etcd-rhel9@sha256:734a21e351fe92a2971aeaae4d26fc1c499070863c826d1129ccf536bc3a1576"
                "registry.redhat.io/openshift-service-mesh/proxyv2-rhel9@sha256:fe1e78971352ddd76ee6f88aa0f4e4ac6d1298da8c960f877ae9f883c291dfd6"
              )

              num_images=${#all_images[@]}
              num_buckets=${NUM_BUCKETS}

              echo "Extracted ${num_images} images"
              echo "Splitting into ${num_buckets} buckets..."

              # Split images into bucket files (round-robin)
              for ((i=0; i<num_buckets; i++)); do
                bucket_file="/var/workdir/artifact-data/bucket-${i}.txt"
                > "${bucket_file}"  # Create empty file

                # Add images to this bucket
                for ((j=i; j<num_images; j+=num_buckets)); do
                  echo "${all_images[$j]}" >> "${bucket_file}"
                done

                bucket_size=$(wc -l < "${bucket_file}")
                echo "Bucket ${i}: ${bucket_size} images"
              done

              echo "Split complete!"
              echo "Bucket files created:"
              ls -lh /var/workdir/artifact-data/
          # Step 2: Push as OCI trusted artifact
          - name: create-trusted-artifact
            image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:aa601d847eafa87747894b770eff43b47cffe2cc39059bb345ee58b378473b8f
            args:
              - create
              - --store
              - $(params.output-image)-fips-images
              - $(results.IMAGES_ARTIFACT.path)=/var/workdir/artifact-data

          # Step 3: Generate bucket indices
          - name: generate-bucket-indices
            image: quay.io/konflux-ci/konflux-test:v1.4.41@sha256:afea44d83043be7f528ec2cacaeb0c3b69cdafdd86a1b930957def38400f8a6c
            env:
              - name: NUM_BUCKETS
                value: $(params.NUM_BUCKETS)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              # The artifact reference was already written by build-trusted-artifacts
              # Just verify it exists
              if [ -f "$(results.IMAGES_ARTIFACT.path)" ]; then
                artifact_ref=$(cat "$(results.IMAGES_ARTIFACT.path)")
                echo "Trusted artifact created: ${artifact_ref}"
              else
                echo "ERROR: IMAGES_ARTIFACT result not found"
                exit 1
              fi

              # Generate bucket indices
              echo "Generating bucket indices..."
              num_buckets=${NUM_BUCKETS}

              indices_json="["
              for ((i=0; i<num_buckets; i++)); do
                if [ $i -gt 0 ]; then
                  indices_json+=","
                fi
                indices_json+="\"${i}\""
              done
              indices_json+="]"

              echo "Generated bucket indices: ${indices_json}"
              echo -n "${indices_json}" > "$(results.BUCKET_INDICES.path)"
    #
    # TASK 2: Matrix FIPS check - pulls artifact and processes bucket
    #
    - name: fips-check-buckets
      timeout: "4h"
      runAfter:
        - prepare-images-and-buckets
      params:
      - name: IMAGES_ARTIFACT
        value: "$(tasks.prepare-images-and-buckets.results.IMAGES_ARTIFACT)"
      - name: TARGET_OCP_VERSION
        value: ""
      - name: MAX_PARALLEL
        value: $(params.MAX_PARALLEL)
      matrix:
        params:
          - name: BUCKET_INDEX
            value: $(tasks.prepare-images-and-buckets.results.BUCKET_INDICES[*])
      taskSpec:
        params:
          - name: BUCKET_INDEX
            type: string
          - name: IMAGES_ARTIFACT
            type: string
          - name: TARGET_OCP_VERSION
            type: string
          - name: MAX_PARALLEL
            type: string 
        volumes:
          - name: workdir
            emptyDir: {}
        stepTemplate:
          volumeMounts:
            - name: workdir
              mountPath: /var/workdir
        steps:
          # Step 1: Create directory for artifact extraction
          - name: prepare-workdir
            image: quay.io/konflux-ci/konflux-test:v1.4.41@sha256:afea44d83043be7f528ec2cacaeb0c3b69cdafdd86a1b930957def38400f8a6c
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              mkdir -p /var/workdir/artifact-data
              echo "Created /var/workdir/artifact-data directory"

          # Step 2: Pull the OCI artifact
          - name: use-trusted-artifact
            image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:aa601d847eafa87747894b770eff43b47cffe2cc39059bb345ee58b378473b8f
            args:
              - use
              - $(params.IMAGES_ARTIFACT)=/var/workdir/artifact-data
          # Step 3: Read bucket file and prepare input files for FIPS check
          - name: prepare-bucket-images
            image: quay.io/konflux-ci/konflux-test:v1.4.41@sha256:afea44d83043be7f528ec2cacaeb0c3b69cdafdd86a1b930957def38400f8a6c
            env:
              - name: BUCKET_INDEX
                value: $(params.BUCKET_INDEX)
              - name: TARGET_OCP_VERSION
                value: $(params.TARGET_OCP_VERSION)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              echo "=========================================="
              echo "FIPS Check - Bucket ${BUCKET_INDEX}"
              echo "=========================================="

              # Read bucket file directly
              bucket_file="/var/workdir/artifact-data/bucket-${BUCKET_INDEX}.txt"

              if [ ! -f "${bucket_file}" ]; then
                echo "ERROR: Bucket file not found at ${bucket_file}"
                echo "Available files:"
                ls -la /var/workdir/artifact-data/ || true
                exit 1
              fi

              # Read images from bucket file
              readarray -t bucket_images < "${bucket_file}"
              num_bucket_images=${#bucket_images[@]}

              echo "Bucket file: ${bucket_file}"
              echo "This bucket contains: ${num_bucket_images} images"

              # Write images to file for FIPS check stepaction
              mkdir -p /tekton/home
              printf '%s\n' "${bucket_images[@]}" > /tekton/home/unique_related_images.txt

              # Write target OCP version if provided
              if [ -n "${TARGET_OCP_VERSION}" ]; then
                echo -n "${TARGET_OCP_VERSION}" > /tekton/home/target_ocp_version.txt
                echo "Target OCP version: ${TARGET_OCP_VERSION}"
              fi

              echo "Prepared ${num_bucket_images} images for FIPS compliance check"
              echo "=========================================="
          # Step 4: Run FIPS operator check
          - name: fips-operator-check-step-action
            params:
              - name: MAX_PARALLEL
                value: $(params.MAX_PARALLEL)
            computeResources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "2"
                memory: 4Gi
            ref:
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions
                - name: revision
                  value: ac78bc7b6ea4d34781a4cff44ae9647745e2e65d
                - name: pathInRepo
                  value: stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
              resolver: git      
            computeResources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "1"
                memory: 2Gi  
    workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-testrepo-2-test-tasl-upgrade
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
